"""
doc_handler.py — Document creation & automation for Friday.
Creates styled Word documents from AI-generated content.
"""
import os
import re
import json
import datetime
from pathlib import Path
from docx import Document
from docx.shared import Pt, RGBColor, Inches, Cm
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml.ns import qn
from docx.oxml import OxmlElement


def _load_prefs():
    try:
        with open("chira_preferences.json") as f:
            return json.load(f)
    except:
        return {}


def get_docs_folder():
    prefs = _load_prefs()
    folder = prefs.get("docs_folder", os.path.expanduser("~/Documents"))
    os.makedirs(folder, exist_ok=True)
    return folder


def _safe_filename(title):
    """Convert title to a safe filename."""
    safe = re.sub(r'[^a-zA-Z0-9 _\-]', '', title)
    return safe.strip()[:60]


def _add_horizontal_line(doc):
    """Add a styled horizontal divider."""
    p = doc.add_paragraph()
    pPr = p._p.get_or_add_pPr()
    pBdr = OxmlElement('w:pBdr')
    bottom = OxmlElement('w:bottom')
    bottom.set(qn('w:val'), 'single')
    bottom.set(qn('w:sz'), '6')
    bottom.set(qn('w:space'), '1')
    bottom.set(qn('w:color'), '00BFFF')
    pBdr.append(bottom)
    pPr.append(pBdr)
    return p


def create_doc_from_content(title, content, open_after=True):
    """
    Create a professionally styled Word document from AI content.
    Supports markdown-style headers (# ## ###), bullet lists (- *), numbered lists.
    Returns the saved filepath.
    """
    doc = Document()

    # ── Page margins ──
    for section in doc.sections:
        section.top_margin    = Cm(2.5)
        section.bottom_margin = Cm(2.5)
        section.left_margin   = Cm(3)
        section.right_margin  = Cm(3)

    # ── Title ──
    title_para = doc.add_heading(title, 0)
    title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    # Color the title
    for run in title_para.runs:
        run.font.color.rgb = RGBColor(0, 100, 200)
        run.font.size = Pt(24)

    # ── Metadata line ──
    meta = doc.add_paragraph()
    meta.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = meta.add_run(
        f"Generated by Friday AI  |  {datetime.datetime.now().strftime('%B %d, %Y  %I:%M %p')}"
    )
    run.font.color.rgb = RGBColor(120, 120, 120)
    run.font.size = Pt(9)
    run.italic = True

    _add_horizontal_line(doc)
    doc.add_paragraph()  # spacer

    # ── Parse & render content ──
    lines = content.split('\n')
    for line in lines:
        stripped = line.strip()
        if not stripped:
            doc.add_paragraph()
            continue

        if stripped.startswith('### '):
            doc.add_heading(stripped[4:], level=3)
        elif stripped.startswith('## '):
            doc.add_heading(stripped[3:], level=2)
        elif stripped.startswith('# '):
            doc.add_heading(stripped[2:], level=1)
        elif stripped.startswith(('- ', '* ')):
            p = doc.add_paragraph(stripped[2:], style='List Bullet')
            p.runs[0].font.size = Pt(11)
        elif re.match(r'^\d+[\.\)]\s', stripped):
            text = re.sub(r'^\d+[\.\)]\s', '', stripped)
            p = doc.add_paragraph(text, style='List Number')
            p.runs[0].font.size = Pt(11)
        elif stripped.startswith('**') and stripped.endswith('**'):
            # Bold line
            p = doc.add_paragraph()
            run = p.add_run(stripped.strip('*'))
            run.bold = True
            run.font.size = Pt(11)
        else:
            p = doc.add_paragraph(stripped)
            p.runs[0].font.size = Pt(11) if p.runs else None

    _add_horizontal_line(doc)

    # ── Footer note ──
    footer_p = doc.add_paragraph()
    footer_p.alignment = WD_ALIGN_PARAGRAPH.RIGHT
    run = footer_p.add_run("Created by Friday — Your AI Assistant")
    run.font.color.rgb = RGBColor(150, 150, 150)
    run.font.size = Pt(8)
    run.italic = True

    # ── Save ──
    folder = get_docs_folder()
    filename = _safe_filename(title) + ".docx"
    filepath = os.path.join(folder, filename)
    doc.save(filepath)
    print(f"[DOC] Saved: {filepath}")

    if open_after:
        os.startfile(filepath)

    return filepath


def get_last_created_doc():
    """Return path of the most recently modified .docx in Documents folder."""
    folder = get_docs_folder()
    docs = sorted(
        Path(folder).glob("*.docx"),
        key=lambda f: f.stat().st_mtime,
        reverse=True
    )
    return str(docs[0]) if docs else None


def append_to_last_doc(text):
    """Append text to the most recently saved document."""
    filepath = get_last_created_doc()
    if not filepath:
        return None
    doc = Document(filepath)
    doc.add_paragraph(text)
    doc.save(filepath)
    return filepath
